version: "3.8"

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000"
    environment:
      - SERVICE_FQDN_CHATBOT
      - PORT=8000
      - LLM_PROVIDER_KEY=${LLM_PROVIDER_KEY}
      - BASE_URL=${BASE_URL}
      - MODEL=${MODEL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST-mongodb}
      - MONGO_PORT=${MONGO_PORT}
      - WOOCOMMERCE_URL=${WOOCOMMERCE_URL}
      - WOOCOMMERCE_CONSUMER_KEY=${WOOCOMMERCE_CONSUMER_KEY}
      - WOOCOMMERCE_CONSUMER_SECRET=${WOOCOMMERCE_CONSUMER_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  mongodb_data:
